### PR TITLE
pdksync externalisation fixes

### PR DESCRIPTION
**Pull request by DavidS**
These changes allow me to use pdksync in a separate repo with all configs in that git repo. I'll add docs once I have figured out the details.

### CODE REVIEW

**Comment by DavidS** [comment]
https://github.com/DavidS/pdksync_configs has a basic configs repo using these changes. With the last commit in this branch here, we can also add a `pdksync.yml` file there and have its settings be used. This fixes the issue where organisational users would have to have a pdksync.conf file in their home and distribute that to all folks in their org, and for folks who need to work with multiple organisations, like puppetlabs+voxpupuli.

**Comment by eimlav** [comment]
Hey @DavidS thanks for contributing these changes. They all look good to me. Nice work!

**Comment by DavidS** [comment]
rebased and documented

**Comment by carabasdaniel** [comment]
👍

**Pull request merged**
